# Generated by Django 3.2.9 on 2021-11-30 01:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco', models.CharField(max_length=255, verbose_name='Endereço')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('paciente', 'paciente'), ('medico', 'medico')], default='paciente', max_length=255, verbose_name='tipo')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidade', models.CharField(blank=True, max_length=255, null=True, verbose_name='Especialidade')),
                ('duracao_consulta', models.IntegerField(default=60, verbose_name='Duração da Consulta')),
                ('clinica', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clinica', to='core.clinica')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='core.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario_inicio', models.DateTimeField(auto_now_add=True, verbose_name='Horário de Inicio')),
                ('horario_fim', models.DateTimeField(blank=True, null=True, verbose_name='Horário Encerramento')),
                ('medico', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medico', to='core.profile')),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paciente', to='core.profile')),
            ],
        ),
    ]
