# Generated by Django 3.2.9 on 2021-12-07 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profile_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='nome',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='nome'),
        ),
    ]
